version: "3"
services:
  app:
    image: dlehdrb/restaurant_search:latest
    ports:
      - "8081:8081"
    volumes:
      - home/ec2-user:/
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"