version: "3"
services:
  app:
    image: dlehdrb/restaurant_search:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"