version: "3"
services:
  app:
    image: dlehdrb/restaurant_search:latest
    ports:
      - "8081:8081"
    volumes:
      - /home/ec2-user:/home/ec2-user
    environment:
      - REDIS_HOST = 3.36.66.213
      - REDIS_PORT = 6379
      - REDIS_PASSWORD = $${REDIS_PASSWORD}