spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;
    username: test
    password: test


#spring:
#  datasource:
#    url: jdbc:postgresql://db.eweozkojxnxiruhfwlwj.supabase.co:5432/postgres?user=postgres&password=DZcheNYX9FDJp9sI
#    username: postgres
#    password: DZcheNYX9FDJp9sI
#  jpa:
#    hibernate:
#      ddl-auto: update